[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "4tFoBRn2KreUN5wemJXiHs1pAjvhMt4cmEJwUSNKmNLB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/loky/.config/solana/loky-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
